### ISSUE TITLE
Warning message with matplotlib 2.1.1-2ubuntu3

### ISSUE THREAD

**Issue by ag-ckt** [tomduck/electrostatics#1]
Warning (from warnings module):
  File "/usr/lib/python3/dist-packages/matplotlib/cbook/deprecation.py", line 106
    warnings.warn(message, mplDeprecation, stacklevel=1)
MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
>>>

**Comment by tomduck** [comment]
This issue is now fixed.  Thanks for the report!  Cheers, Tom.
